version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cp .env.aws.backend.example .env.aws.backend
      - docker-compose -f docker-compose.testing.yml up --build -d
  post_build:
    commands:
      - docker exec src_backend_1 npm run test
      - docker exec src_vue_1 apt-get update
      - docker exec src_vue_1 apt-get install curl -y
      - docker exec src_vue_1 apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y
      - docker exec src_vue_1 cp cypress.test.json cypress.json
      - docker exec src_vue_1 npx cypress run --headless
      - echo Build completed on `date`
artifacts:
    files:
      - '**/*'