version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cp .env.aws.backend.example .env.aws.backend
      - docker-compose up --build -d
  post_build:
    commands:
      - docker exec -it zerowalletrecoverable_backend_1 sh
      - npm run test
      - echo Build completed on `date`
artifacts:
    files: 
      - imagedefinitions.json