version: 0.2

env:
    variables:
        NODE_ENV: 'development'
        VUE_APP_BACKEND_ENDPOINT: 'https://wallet-api-dev.morpher.com'
        VUE_APP_I18N_DEFAULT_LOCALE: 'en'
        VUE_APP_I18N_SUPPORTED_LOCALE: '["en", "ru", "bs"]'
        VUE_APP_GOOGLE_ANALYTICS_API_KEY: 'G-SQX15ZBECV'
    secrets-manager:
        VUE_APP_GOOGLE_APP_ID: "arn:aws:secretsmanager:eu-central-1:612970435624:secret:environment_dev-GRZlqk:WALLET_GOOGLE_APP_ID::"
        VUE_APP_FACEBOOK_APP_ID: "arn:aws:secretsmanager:eu-central-1:612970435624:secret:environment_dev-GRZlqk:WALLET_FACEBOOK_APP_ID::"
        VUE_APP_VK_APP_ID: "arn:aws:secretsmanager:eu-central-1:612970435624:secret:environment_dev-GRZlqk:WALLET_VK_APP_ID::"
        VUE_APP_SENTRY_ENDPOINT: "arn:aws:secretsmanager:eu-central-1:612970435624:secret:environment_dev-GRZlqk:WALLET_SENTRY_ENDPOINT::"
        VUE_APP_RELEASE_VERSION: "arn:aws:secretsmanager:eu-central-1:612970435624:secret:environment_dev-GRZlqk:WALLET_SENTRY_VERSION::"

phases:
    install:
        runtime-versions:
            nodejs: 14
        commands:
            - pip install --upgrade pip
            - pip install --upgrade awscli
    pre_build:
        commands:
            - cd vue
            - npm install
    build:
        commands:
            - npm run lint
            - npm run build
    post_build:
        commands:
            - find . -name \*.map -type f -delete

artifacts:
    files:
        - '**/*'
    base-directory: 'vue/dist*'

