version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run env:dev
      - npm run build
      - cp .env dist/
      - cp package.json dist/
  post_build:
    commands:
      - echo "post_build step"

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'